import type { Template } from "@/types";

// Static starter set shown until a live `templates` table is connected via
// Supabase (see supabase/migrations/0001_init.sql). Swapping to live data
// only requires fetching from the `templates` table with the same shape.
export const TEMPLATES: Template[] = [
  {
    id: "ai-trends",
    name: "AI Trends",
    category: "AI",
    description: "A sleek carousel breaking down emerging AI trends for your audience.",
    slideCount: 7,
    style: "Minimal",
    previewUrl: "",
    prompt: "Crie um carrossel de 7 slides sobre as principais tendências de inteligência artificial em 2026. Estilo minimalista e premium, fundo escuro.",
  },
  {
    id: "startup-pitch",
    name: "Startup Pitch Deck Post",
    category: "Startup",
    description: "A bold single post to announce your startup's latest milestone.",
    slideCount: null,
    style: "Bold",
    previewUrl: "",
    prompt: "A bold Instagram post announcing a startup funding round, dark background, confident typography, premium tech aesthetic.",
  },
  {
    id: "quarterly-results",
    name: "Quarterly Results",
    category: "Business",
    description: "Present quarterly growth numbers with a clean, corporate carousel.",
    slideCount: 5,
    style: "Corporate",
    previewUrl: "",
    prompt: "Crie um carrossel de 5 slides apresentando os resultados trimestrais de uma empresa, estilo corporativo e limpo.",
  },
  {
    id: "product-launch-ad",
    name: "Product Launch Ad",
    category: "Marketing",
    description: "A high-impact ad creative for a new product drop.",
    slideCount: null,
    style: "Editorial",
    previewUrl: "",
    prompt: "An ad creative announcing a new product launch, editorial photography style, bold headline space, premium mood.",
  },
  {
    id: "market-outlook",
    name: "Market Outlook",
    category: "Finance",
    description: "Explain a financial concept in a structured, trustworthy carousel.",
    slideCount: 8,
    style: "Minimal",
    previewUrl: "",
    prompt: "Crie um carrossel de 8 slides explicando como funciona o mercado de ações para iniciantes. Estilo minimalista, tom educativo e confiável.",
  },
  {
    id: "study-tips",
    name: "Study Tips",
    category: "Education",
    description: "Share practical learning tips in a friendly, structured format.",
    slideCount: 6,
    style: "Warm",
    previewUrl: "",
    prompt: "Crie um carrossel de 6 slides com dicas práticas de estudo para estudantes universitários. Tom amigável e motivador.",
  },
  {
    id: "workout-plan",
    name: "Workout Plan",
    category: "Fitness",
    description: "An energetic carousel walking through a weekly workout split.",
    slideCount: 7,
    style: "Vibrant",
    previewUrl: "",
    prompt: "Create a 7-slide carousel presenting a weekly workout split for beginners. Vibrant, energetic, motivational style.",
  },
  {
    id: "personal-brand-intro",
    name: "Personal Brand Intro",
    category: "Personal Brand",
    description: "Introduce yourself and your work with a confident single post.",
    slideCount: null,
    style: "Minimal",
    previewUrl: "",
    prompt: "A minimalist Instagram post introducing a personal brand and areas of expertise, clean portrait-friendly composition.",
  },
  {
    id: "listing-showcase",
    name: "Listing Showcase",
    category: "Real Estate",
    description: "Showcase a property listing with premium, architectural framing.",
    slideCount: null,
    style: "Premium",
    previewUrl: "",
    prompt: "An Instagram post showcasing a luxury real estate listing, architectural photography style, premium and aspirational mood.",
  },
  {
    id: "recipe-carousel",
    name: "Recipe Carousel",
    category: "Food",
    description: "Walk through a recipe step by step with appetizing visuals.",
    slideCount: 6,
    style: "Warm",
    previewUrl: "",
    prompt: "Create a 6-slide carousel walking through a simple recipe step by step, warm natural lighting, appetizing food photography style.",
  },
  {
    id: "lookbook-post",
    name: "Lookbook Post",
    category: "Fashion",
    description: "A stylish single post for a new fashion collection.",
    slideCount: null,
    style: "Editorial",
    previewUrl: "",
    prompt: "An editorial-style Instagram post for a new fashion collection lookbook, high-fashion photography aesthetic.",
  },
  {
    id: "tech-comparison",
    name: "Tech Comparison",
    category: "Technology",
    description: "Compare two tools or approaches in a clear, structured carousel.",
    slideCount: 5,
    style: "Tech",
    previewUrl: "",
    prompt: "Crie um carrossel de 5 slides comparando duas ferramentas de tecnologia, estilo tecnológico e futurista, fundo escuro.",
  },
];
